version: "3.8"

services:
  resume-app-qa:
    build:
      context: .
      dockerfile: Dockerfile
    image: asawari27/resume-v1-qa:latest
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - GROQ_API_KEY_V1=${GROQ_API_KEY_V1}
      - GROQ_API_KEY_V2=${GROQ_API_KEY_V2}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI_QA}
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_PASSWORD=${GMAIL_PASSWORD}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT_SSL=${SMTP_PORT_SSL}
    volumes:
      - .:/app
    restart: unless-stopped

